version: '3.3'
services:
  jenkins:
    image: jenkins:devopsimage23
    container_name: jenkinsdevops
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
      - JENKINS_ADMIN_ID=${ENV_JENKINS_ADMIN_ID}
      - JENKINS_ADMIN_PASSWORD=${ENV_JENKINS_ADMIN_PASSWORD}
      - GITHUB_USERNAME=${ENV_GITHUB_USERNAME}
      - GITHUB_PASSWORD=${ENV_GITHUB_PASSWORD}
    ports:
      - "8085:8080"
      - "50000:50000"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - ./casc.yaml:/var/jenkins_home/casc.yaml
      - /usr/bin/docker:/usr/bin/docker
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    ports:
      - "8081:8081"
    restart: unless-stopped
    volumes:
      - nexus-data:/nexus-data
  maven:
    build:
      context: .
      dockerfile: ./Dockerfile

volumes:
  jenkins-data:
  nexus-data:
